import { describe, expect, it } from "vitest";
import { CLABEService } from "../clabeService";

describe("CLABEService", () => {
  describe("validate()", () => {
    it("returns false for a CLABE shorter than 18 digits", () => {
      expect(CLABEService.validate("12345678901234567")).toBe(false); // 17 digits
    });

    it("returns false for a CLABE longer than 18 digits", () => {
      expect(CLABEService.validate("1234567890123456789")).toBe(false); // 19 digits
    });

    it("returns false for empty string", () => {
      expect(CLABEService.validate("")).toBe(false);
    });

    it("returns false when the verifier digit is wrong", () => {
      // Generate a valid CLABE, then corrupt the last digit
      const valid = CLABEService.generateStudentCLABE("123", "0001");
      const lastDigit = valid[17];
      // Flip the verifier digit: add 1 mod 10 to force a mismatch
      const wrongVerifier = String((parseInt(lastDigit) + 1) % 10);
      const corrupted = valid.slice(0, 17) + wrongVerifier;
      expect(CLABEService.validate(corrupted)).toBe(false);
    });

    it("validates a round-trip CLABE generated by generateStudentCLABE", () => {
      const clabe = CLABEService.generateStudentCLABE("123", "0001");
      expect(CLABEService.validate(clabe)).toBe(true);
    });

    it("validates multiple different generated CLABEs", () => {
      const inputs: Array<[string, string]> = [
        ["001", "0001"],
        ["256", "9999"],
        ["999", "1234"],
        ["100", "5678"],
      ];
      inputs.forEach(([cc, studentId]) => {
        const clabe = CLABEService.generateStudentCLABE(cc, studentId);
        expect(CLABEService.validate(clabe)).toBe(true);
      });
    });
  });

  describe("generateStudentCLABE()", () => {
    it("always produces an 18-character string", () => {
      const clabe = CLABEService.generateStudentCLABE("456", "9999");
      expect(clabe).toHaveLength(18);
    });

    it("pads a short stpCostCenter to 3 digits", () => {
      const clabe = CLABEService.generateStudentCLABE("1", "0001");
      // Layout: 0-2 BANCO(646), 3-5 PLAZA(180), 6-9 PREFIX(0000), 10-12 cc, 13-16 studentSeq, 17 verifier
      expect(clabe.substring(10, 13)).toBe("001");
    });

    it("uses the last 4 characters of studentId as the student sequence", () => {
      const clabe = CLABEService.generateStudentCLABE("123", "student_1234");
      expect(clabe.substring(13, 17)).toBe("1234");
    });

    it("produces different CLABEs for different student IDs", () => {
      const clabe1 = CLABEService.generateStudentCLABE("123", "0001");
      const clabe2 = CLABEService.generateStudentCLABE("123", "0002");
      expect(clabe1).not.toBe(clabe2);
    });

    it("produces different CLABEs for different cost centers", () => {
      const clabe1 = CLABEService.generateStudentCLABE("100", "0001");
      const clabe2 = CLABEService.generateStudentCLABE("200", "0001");
      expect(clabe1).not.toBe(clabe2);
    });

    it("uses the STP bank code (646) as the first 3 digits", () => {
      const clabe = CLABEService.generateStudentCLABE("123", "0001");
      expect(clabe.substring(0, 3)).toBe("646");
    });
  });
});
