-- supabase/migrations/001_initial_schema_v3.sql
-- Script de esquema v3 para MeCard.
-- Incorpora billeteras, concesionarias, y RLS basadas en roles.

-- ========= FUNCIONES AUXILIARES DE SEGURIDAD =========

-- Obtiene el school_id del usuario autenticado.
CREATE OR REPLACE FUNCTION public.get_current_user_school_id()
RETURNS bigint LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT school_id FROM users WHERE id = auth.uid();
$$;

-- Obtiene el rol del usuario autenticado.
CREATE OR REPLACE FUNCTION public.get_current_user_role()
RETURNS text LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT role FROM users WHERE id = auth.uid();
$$;

-- ========= TABLAS DE ESTRUCTURA Y MULTI-TENANCY =========

-- Tabla de Escuelas (Schools)
CREATE TABLE public.schools (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now()
);

-- Tabla de Concesionarias (Operating Units)
CREATE TABLE public.operating_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id bigint NOT NULL REFERENCES public.schools(id),
    name text NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now()
);

-- Tabla de Perfiles de Usuario (Users/Profiles)
CREATE TABLE public.users (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    school_id bigint NOT NULL REFERENCES public.schools(id),
    role text NOT NULL CHECK (role IN ('school_admin', 'parent', 'concessionaire_staff')),
    full_name text,
    created_at timestamp WITH time zone NOT NULL DEFAULT now()
);

-- Tabla de Estudiantes (Students)
CREATE TABLE public.students (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id bigint NOT NULL REFERENCES public.schools(id),
    student_name text NOT NULL,
    grade_level text,
    created_at timestamp WITH time zone NOT NULL DEFAULT now()
);

-- Tabla de Relaciones Padre-Estudiante (Parent-Student Links)
CREATE TABLE public.parent_student_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    student_id bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    school_id bigint NOT NULL REFERENCES public.schools(id),
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    UNIQUE(parent_user_id, student_id)
);

-- ========= TABLAS FINANCIERAS Y DE OPERACIONES =========

-- Tabla de Billeteras/Perfiles Financieros (Financial Profiles)
CREATE TABLE public.financial_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL UNIQUE REFERENCES public.students(id) ON DELETE CASCADE,
    school_id bigint NOT NULL REFERENCES public.schools(id),
    balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0),
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    updated_at timestamp WITH time zone NOT NULL DEFAULT now() -- Para triggers o lógica de actualización
);

-- Tabla de Productos (Products)
CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id bigint NOT NULL REFERENCES public.schools(id),
    operating_unit_id bigint REFERENCES public.operating_units(id),
    name text NOT NULL,
    price numeric NOT NULL CHECK (price >= 0),
    category text,
    created_at timestamp WITH time zone NOT NULL DEFAULT now()
);

-- Tabla de Transacciones (Transactions)
CREATE TABLE public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id bigint NOT NULL REFERENCES public.schools(id),
    student_id bigint NOT NULL REFERENCES public.students(id),
    product_id bigint REFERENCES public.products(id), -- Nullable para transacciones no relacionadas a productos (ej. depósitos)
    operating_unit_id bigint REFERENCES public.operating_units(id),
    amount numeric NOT NULL,
    type text NOT NULL CHECK (type IN ('deposit', 'purchase', 'refund', 'transfer')),
    status text NOT NULL CHECK (status IN ('pending', 'completed', 'failed', 'cancelled')),
    reference_id text, -- Para IDs de transacciones externas
    created_at timestamp WITH time zone NOT NULL DEFAULT now()
);


-- ========= SEGURIDAD: ROW LEVEL SECURITY (RLS) =========

-- Habilitar RLS en todas las tablas.
ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operating_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parent_student_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS DE ACCESO (SELECT) UNIFICADAS POR ROL

-- Policy for schools
CREATE POLICY "Allow role-based access to schools" ON public.schools
    FOR SELECT USING (id = public.get_current_user_school_id());

-- Policy for operating_units
CREATE POLICY "Allow role-based access to operating_units" ON public.operating_units
    FOR SELECT USING (school_id = public.get_current_user_school_id());

-- Policy for users
CREATE POLICY "Allow role-based access to users" ON public.users
    FOR SELECT USING (school_id = public.get_current_user_school_id());

-- Policy for students
CREATE POLICY "Allow role-based access to students" ON public.students
    FOR SELECT USING (
        CASE
            WHEN public.get_current_user_role() = 'school_admin' THEN
                school_id = public.get_current_user_school_id()
            WHEN public.get_current_user_role() = 'parent' THEN
                id IN (
                    SELECT student_id FROM public.parent_student_links
                    WHERE parent_user_id = auth.uid()
                )
            ELSE
                false
        END
    );

-- Policy for parent_student_links
CREATE POLICY "Allow parents to view their links" ON public.parent_student_links
    FOR SELECT USING (
        parent_user_id = auth.uid() OR
        (school_id = public.get_current_user_school_id() AND public.get_current_user_role() = 'school_admin')
    );

CREATE POLICY "Allow school_admin to insert parent_student_links" ON public.parent_student_links
    FOR INSERT WITH CHECK (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

CREATE POLICY "Allow school_admin to delete parent_student_links" ON public.parent_student_links
    FOR DELETE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- Policy for financial_profiles
CREATE POLICY "Allow role-based access to financial_profiles" ON public.financial_profiles
    FOR SELECT USING (
        CASE
            WHEN public.get_current_user_role() = 'school_admin' THEN
                school_id = public.get_current_user_school_id()
            WHEN public.get_current_user_role() = 'parent' THEN
                student_id IN (
                    SELECT student_id FROM public.parent_student_links
                    WHERE parent_user_id = auth.uid()
                )
            ELSE
                false
        END
    );

CREATE POLICY "Allow school_admin to insert financial_profiles" ON public.financial_profiles
    FOR INSERT WITH CHECK (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

CREATE POLICY "Allow school_admin to update financial_profiles" ON public.financial_profiles
    FOR UPDATE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    ) WITH CHECK (
        school_id = public.get_current_user_school_id()
    );

-- Policy for products
CREATE POLICY "Allow role-based access to products" ON public.products
    FOR SELECT USING (school_id = public.get_current_user_school_id());

CREATE POLICY "Allow school_admin to insert products" ON public.products
    FOR INSERT WITH CHECK (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

CREATE POLICY "Allow school_admin to update products" ON public.products
    FOR UPDATE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    ) WITH CHECK (
        school_id = public.get_current_user_school_id()
    );

CREATE POLICY "Allow school_admin to delete products" ON public.products
    FOR DELETE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- Policy for transactions
CREATE POLICY "Allow role-based access to transactions" ON public.transactions
    FOR SELECT USING (
        CASE
            WHEN public.get_current_user_role() = 'school_admin' THEN
                school_id = public.get_current_user_school_id()
            WHEN public.get_current_user_role() = 'parent' THEN
                student_id IN (
                    SELECT student_id FROM public.parent_student_links
                    WHERE parent_user_id = auth.uid()
                )
            ELSE
                false
        END
    );

CREATE POLICY "Allow school_admin to insert transactions" ON public.transactions
    FOR INSERT WITH CHECK (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() IN ('school_admin', 'concessionaire_staff')
    );

CREATE POLICY "Allow school_admin to update transactions" ON public.transactions
    FOR UPDATE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    ) WITH CHECK (
        school_id = public.get_current_user_school_id()
    );

CREATE POLICY "Allow school_admin to delete transactions" ON public.transactions
    FOR DELETE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- ========= RENDIMIENTO: ÍNDICES =========

-- Índices en claves foráneas para acelerar JOINs.
CREATE INDEX ON public.users (school_id);
CREATE INDEX ON public.students (school_id);
CREATE INDEX ON public.parent_student_links (parent_user_id);
CREATE INDEX ON public.parent_student_links (student_id);
CREATE INDEX ON public.parent_student_links (school_id);
CREATE INDEX ON public.operating_units (school_id);
CREATE INDEX ON public.financial_profiles (school_id);
CREATE INDEX ON public.financial_profiles (student_id);
CREATE INDEX ON public.products (school_id);
CREATE INDEX ON public.products (operating_unit_id);
CREATE INDEX ON public.transactions (school_id);
CREATE INDEX ON public.transactions (student_id);
CREATE INDEX ON public.transactions (product_id);
CREATE INDEX ON public.transactions (operating_unit_id);
CREATE INDEX ON public.transactions (type);
CREATE INDEX ON public.transactions (status);
