-- supabase/migrations/002_add_limits_alerts_tables.sql
-- Añade tablas para spending limits y alerts
-- Ejecutar después de 001_initial_schema.sql

-- ========= TABLA DE LÍMITES DE GASTO =========

CREATE TABLE public.spending_limits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    student_id bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    daily_limit numeric NOT NULL DEFAULT 100 CHECK (daily_limit > 0),
    monthly_limit numeric NOT NULL DEFAULT 1000 CHECK (monthly_limit > 0),
    category_limits jsonb, -- Para límites por categoría (opcional)
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    updated_at timestamp WITH time zone NOT NULL DEFAULT now(),
    UNIQUE(school_id, student_id)
);

-- ========= TABLA DE CONFIGURACIÓN DE ALERTAS =========

CREATE TABLE public.alert_configs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    student_id bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    daily_alert_threshold numeric NOT NULL DEFAULT 50 CHECK (daily_alert_threshold > 0),
    monthly_alert_threshold numeric NOT NULL DEFAULT 500 CHECK (monthly_alert_threshold > 0),
    low_balance_threshold numeric NOT NULL DEFAULT 10 CHECK (low_balance_threshold >= 0),
    suspicious_activity_threshold integer NOT NULL DEFAULT 5 CHECK (suspicious_activity_threshold > 0),
    notify_parent boolean NOT NULL DEFAULT true,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    updated_at timestamp WITH time zone NOT NULL DEFAULT now(),
    UNIQUE(school_id, student_id)
);

-- ========= TABLA DE ALERTAS =========

CREATE TABLE public.alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    parent_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    student_id bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    type text NOT NULL CHECK (type IN ('high_spending', 'limit_exceeded', 'suspicious_activity', 'balance_low')),
    title text NOT NULL,
    message text NOT NULL,
    severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
    is_read boolean NOT NULL DEFAULT false,
    metadata jsonb,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    read_at timestamp WITH time zone
);

-- ========= ROW LEVEL SECURITY (RLS) =========

-- Habilitar RLS en todas las nuevas tablas
ALTER TABLE public.spending_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- ========= POLÍTICAS PARA SPENDING_LIMITS =========

-- SELECT: school_admin ve todos, parents no pueden ver (no es información suya)
CREATE POLICY "Allow school_admin to view spending_limits" ON public.spending_limits
    FOR SELECT USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- INSERT: solo school_admin
CREATE POLICY "Allow school_admin to insert spending_limits" ON public.spending_limits
    FOR INSERT WITH CHECK (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- UPDATE: solo school_admin
CREATE POLICY "Allow school_admin to update spending_limits" ON public.spending_limits
    FOR UPDATE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    ) WITH CHECK (
        school_id = public.get_current_user_school_id()
    );

-- DELETE: solo school_admin
CREATE POLICY "Allow school_admin to delete spending_limits" ON public.spending_limits
    FOR DELETE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- ========= POLÍTICAS PARA ALERT_CONFIGS =========

-- SELECT: school_admin ve todos
CREATE POLICY "Allow school_admin to view alert_configs" ON public.alert_configs
    FOR SELECT USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- INSERT: solo school_admin
CREATE POLICY "Allow school_admin to insert alert_configs" ON public.alert_configs
    FOR INSERT WITH CHECK (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- UPDATE: solo school_admin
CREATE POLICY "Allow school_admin to update alert_configs" ON public.alert_configs
    FOR UPDATE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    ) WITH CHECK (
        school_id = public.get_current_user_school_id()
    );

-- DELETE: solo school_admin
CREATE POLICY "Allow school_admin to delete alert_configs" ON public.alert_configs
    FOR DELETE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- ========= POLÍTICAS PARA ALERTS =========

-- SELECT: parents ven solo sus alertas, school_admin ve todas
CREATE POLICY "Allow parents and admin to view alerts" ON public.alerts
    FOR SELECT USING (
        CASE
            WHEN public.get_current_user_role() = 'school_admin' THEN
                school_id = public.get_current_user_school_id()
            WHEN public.get_current_user_role() = 'parent' THEN
                parent_user_id = auth.uid()
            ELSE
                false
        END
    );

-- INSERT: solo system (via services con SECURITY DEFINER)
CREATE POLICY "Allow admin to insert alerts" ON public.alerts
    FOR INSERT WITH CHECK (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- UPDATE: parents marcan como leídas, admin puede actualizar
CREATE POLICY "Allow parents to mark alerts as read" ON public.alerts
    FOR UPDATE USING (
        CASE
            WHEN public.get_current_user_role() = 'parent' THEN
                parent_user_id = auth.uid()
            WHEN public.get_current_user_role() = 'school_admin' THEN
                school_id = public.get_current_user_school_id()
            ELSE
                false
        END
    ) WITH CHECK (
        CASE
            WHEN public.get_current_user_role() = 'parent' THEN
                parent_user_id = auth.uid()
            WHEN public.get_current_user_role() = 'school_admin' THEN
                school_id = public.get_current_user_school_id()
            ELSE
                false
        END
    );

-- DELETE: solo admin
CREATE POLICY "Allow admin to delete alerts" ON public.alerts
    FOR DELETE USING (
        school_id = public.get_current_user_school_id() AND
        public.get_current_user_role() = 'school_admin'
    );

-- ========= ÍNDICES PARA PERFORMANCE =========

-- spending_limits
CREATE INDEX ON public.spending_limits (school_id);
CREATE INDEX ON public.spending_limits (student_id);

-- alert_configs
CREATE INDEX ON public.alert_configs (school_id);
CREATE INDEX ON public.alert_configs (student_id);

-- alerts
CREATE INDEX ON public.alerts (school_id);
CREATE INDEX ON public.alerts (parent_user_id);
CREATE INDEX ON public.alerts (student_id);
CREATE INDEX ON public.alerts (is_read);
CREATE INDEX ON public.alerts (created_at);
CREATE INDEX ON public.alerts (type);
